export const JOB_DATA_REQUEST = "JOB_DATA_REQUEST";
export const JOB_DATA_SUCCESS = "JOB_DATA_SUCCESS";
export const JOB_DATA_FAILURE = "JOB_DATA_FAILURE";

export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAILURE = "USER_REG_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const JOB_APPLY_REQUEST = "JOB_APPLY_REQUEST";
export const JOB_APPLY_SUCCESS = "JOB_APPLY_SUCCESS";
export const JOB_APPLY_FAILURE = "JOB_APPLY_FAILURE";
export const JOB_APPLY_CLEAR = "JOB_APPLY_CLEAR";

export const USER_JOB_REQUEST = "USER_JOB_REQUEST";
export const USER_JOB_SUCCESS = "USER_JOB_SUCCESS";
export const USER_JOB_FAILURE = "USER_JOB_FAILURE";
