export const JOB_DATA_REQUEST = "JOB_DATA_REQUEST";
export const JOB_DATA_SUCCESS = "JOB_DATA_SUCCESS";
export const JOB_DATA_FAILURE = "JOB_DATA_FAILURE";

export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAILURE = "USER_REG_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
